[package]
name = "galoy-client"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

# This feature is to enforce clippy warnings as errors
fail-on-warnings = []

[dependencies]
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
anyhow = "1.0.66"
reqwest = { version = "0.11.13", features = ["json", "blocking"] }
graphql_client = { version = "0.11.0", features = ["reqwest-blocking", "reqwest"] }
clap     = { version =  "4.0", features = ["derive", "env"] }
url = { version = "2.3.1", features = ["serde"] }
log = "0.4.17"
jsonwebtoken = "8"
csv = "1.1.6"
rust_decimal = "1.27.0"
rust_decimal_macros = "1.20"
thiserror = "1.0.37"
actix-web = "4.2.1"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tera = "1.17.1"
actix-web-static-files = "4.0.0"
static-files = "0.2.3"

[build-dependencies]
static-files = "0.2.3"
