query QueryMe {
  me {
    id
    username
    phone
    defaultAccount {
      __typename
      id
      defaultWalletId
      displayCurrency
      wallets {
        __typename
        id
        balance
        walletCurrency
      }
    }
  }
}
