name: 'Check Test'

on:
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Check Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test code
        run: make test