name: "E2E Test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - uses: actions/checkout@v3
      - name: Setup cache for cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run e2e
        run: make e2e
