name: "E2E Test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker environment
        run: |
          echo "HOST_PROJECT_PATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "GALOY_QUICKSTART_PATH=vendor/galoy-quickstart" >> $GITHUB_ENV

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Setup cache for cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose

      - name: Run e2e
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          retry_on: error
          max_attempts: 3
          command: make e2e
